language: node_js
node_js:
  - '10'
os: linux
env:
  - ESLINT_VERSION=6
branches:
  only:
  - master
cache:
  directories:
  - node_modules
matrix:
  include:
  - env: PACKAGE=resolvers/node
    node_js: 10
  fast_finish: true
before_install:
  - 'nvm install-latest-npm'
install:
  - npm install
script:
  - 'npm run lint'
  - 'npm run test'