language: node_js
node_js:
  - '10'
os: linux
env:
  - ESLINT_VERSION=6
branches:
  only:
  - master
cache:
  directories:
  - node_modules
matrix:
  include:
  - env: PACKAGE=resolvers/node
    node_js: 10
  fast_finish: true
install:
  - yarn
script:
  - 'yarn lint'
  - 'yarn test --verbose "--no-cache"'